2023-2-grupo-37/config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'rooms/index'
  root 'pagina_principal#index'
  # PAGINAS PRINCIPALES (cuenta, inicio, etc.)
  get 'pagina_principal/index'
  get '/cuenta', to: 'pagina_principal#cuenta'
  get '/inicio', to: 'pagina_principal#index'

  # Usuarios
  devise_scope :user do
    get 'users', to: 'devise/sessions#new'
  end
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }, 
                   path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  get 'user/:id', to: 'users#show', as: 'user'

  # Chat
  resources :rooms do
    resources :messages
  end

  resources :pins

  get 'hello_world/index'

  # PRODUCTOS 
  get 'productos', to: 'productos#index'
  get '/productos/new', to: 'productos#new'
  get 'productos/:id', to: 'productos#show', as: 'producto'
  get 'productos/:id/eliminar', to: 'productos#destroy', as: 'eliminar_producto'
  get 'productos/:id/editar', to: 'productos#page_update', as: 'editar_producto'
  get 'productos/:id/favorito', to: 'productos#favoritos', as: 'favoritos_usuario'
  patch 'productos/:id', to: 'productos#update', as: 'update_producto'
  post 'productos', to: 'productos#create'
  get 'producto/populares', to: "productos#mas_visitados", as: "mas_visitados"

  # INTERCAMBIOS
  get 'intercambios', to: 'intercambios#index'
  get 'intercambios/:id/create', to: 'intercambios#create', as: 'crear_intercambio'
  get 'intercambios/:id/eliminar', to: 'intercambios#destroy', as: 'eliminar_intercambio'
  get 'intercambios/:id/editar', to: 'intercambios#page_update', as: 'editar_intercambio'
  patch 'intercambios/:id', to: 'intercambios#update', as: 'update_intercambio'
  post 'intercambios/:id', to: 'intercambios#create', as: 'postear_intercambio'

  # REPORTES
  get "reportes/:id/new", to: "reportes#new", as: "nuevo_reporte"
  get "reportes/:id", to: "reportes#show", as: "ver_reportes"
  post "reportes/:id", to: "reportes#create", as: "crear_reporte"
  get "reporte/:id/editar", to: "reportes#page_update", as: "editar_reporte"
  patch "reporte/:id", to: "reportes#update", as: "actualizar_reporte"
  get "reporte/:id/eliminar", to: "reportes#destroy", as: "eliminar_reporte" 

  # ADMINISTRADOR
  get '/admin', to: 'admins#index'
  get '/admin/productos', to: 'admins#productos'
  get '/admin/reportes', to: 'admins#reportes'
  get '/admin/intercambios', to: 'admins#intercambios'
  get '/admin/usuarios', to: 'admins#usuarios'
  
  # USUARIOS
  get "usuarios/:id/editar", to: "users#page_update", as: "editar_usuario"
  get "usuario/:id", to: "users#cuenta_visita", as: "ver_usuario"
  post "usuario/:id", to: "users#calificar_usuario", as: "calificar_usuario"
  patch "usuarios/:id", to: "users#update", as: "actualizar_usario"
  get "usuarios/:id/eliminar", to: "users#destroy", as: "eliminar_usuario"
  get "usuario/:id/favoritos",  to: "users#favoritos", as: "mostrar_favoritos"
  get "usuario/:id/eliminar_favorito", to: "productos#eliminar_favorito", as: "eliminar_favorito"
end

2023-2-grupo-37/app/models/reporte.rb
class Reporte < ApplicationRecord
  belongs_to :producto
  belongs_to :user

  validates :descripcion, length: { maximum: 200 }

  after_create :verificar_reportes

  private

  def verificar_reportes
    if producto.reportes.count >= 3
      producto.destroy
    end
  end
end

2023-2-grupo-37/app/controllers/reportes_controller.rb
  class ReportesController < ApplicationController

    def show
      @producto = Producto.find(params[:id])
      @reportes = @producto.reportes
    end

    def new
      @reporte = Reporte.new
    end

    def create
      @producto = Producto.find(params[:id])
    
      if @producto.reportes.count >= 3
        @producto.destroy
        redirect_to productos_path, 
                    notice: 'El producto ha sido eliminado debido a que ha superado el número máximo de reportes.'
      else
        @reporte = Reporte.new(reporte_params)
        @reporte.producto = @producto
        @reporte.user = current_user 
    
        if @reporte.save
          redirect_to @producto, notice: 'Reporte enviado con éxito.'
        else
          render :new, status: :unprocessable_entity
        end
      end
    end

    def page_update
      @reporte = Reporte.find(params[:id])
    end

    #def update
    #  @reporte = Reporte.find(params[:id])
    # @producto = Producto.find(@reporte.producto_id)
    # if @reporte.update(reporte_params)
    #   redirect_to root_path, notice: 'Reporte acutualizado con exito.'
    # else
    #   render :new, status: :unprocessable_entity
    # end
    #end

    def destroy
      @reporte = Reporte.find(params[:id])
      @reporte.destroy
      redirect_to root_path, notice: 'Reporte eliminado con éxito.'
    end

  private

    def reporte_params
      params.require(:reporte).permit(:producto_id, :user_id, :descripcion)
    end
end

2023-2-grupo-37/app/helpers/reportes_helper.rb
module ReportesHelper
end

2023-2-grupo-37/app/views/reportes/create.html.erb
<h1>Reporte Enviado</h1>
<p>Tu reporte ha sido enviado con éxito. ¡Gracias por tu contribución!</p>

<%= link_to 'Volver a Productos', productos_path %>

2023-2-grupo-37/app/views/reportes/new.html.erb
<body>
  <%= render 'shared/header' %>
  <main>
    <div class="fondo_forms">
      <div class="Bienvenida">
          <h1>Reportar Producto</h1>
      </div>
      <%= form_with(model: @reporte, url: crear_reporte_path, method: "POST") do |form| %>
        <div class="divform">
          <div>
            <textarea type="text" id="descripcion" name="reporte[descripcion]" 
            placeholder="Explicación del reporte de este producto" class="textarea"
            style="resize: none;"></textarea><br>
          </div>
          <button type="submit" class="custom-button">
            Enviar Reporte
            <div class="arrow-wrapper">
              <div class="arrow"></div>
            </div>
          </button>
        </div>
      <% end %>
    </div>
  </main>
</body>

2023-2-grupo-37/app/views/reportes/page_update.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Proyecto Grupo 37</title>
    <link rel="stylesheet" href="styles.css">
  </head>
  <body>
    <%= render 'shared/header' %>
    <main>
      <div class="fondo_forms">
        <div class='Bienvenida'>
          <h1>Editar Reporte</h1>
        </div>
          <%= form_with url: "/reporte/#{@reporte.id}", model: @reporte, method: :patch do |form|%>
            <div class="divform">
              <div>
                <input type="text" id="nombre" 
                name="reporte[descripcion]" placeholder="Explicación Reporte" 
                value="<%= @reporte.descripcion %>" class="input">
              </div>

              <button type="submit" class="custom-button">
                Enviar Cambios
                <div class="arrow-wrapper">
                  <div class="arrow"></div>
                </div>
              </button>
          <% end %>
      </div>
    </main>
  </body>
</html>

2023-2-grupo-37/app/views/reportes/show.html.erb
<body>
  <%= render 'shared/header' %>
  <main>
    <% if @reportes.any? %>
      <div class="Bienvenida">
            <h2>Reportes del producto: <%= @producto.nombre %></h2>
      </div>
      <section class="element-admin">
          <% @reportes.each do |reporte| %>
            <div class="elements-admin">
              <h2>Motivo Reporte:</h2>
              <p><%= reporte.descripcion %></p>
            </div>
          <% end %>
      </section>
    <% else %>
      <div class="btn">No hay reportes para este producto</div>
      <%= link_to "Back", :back %>
    <% end %>
    
  </main>
</body>