2023-2-grupo-37/config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'rooms/index'
  root 'pagina_principal#index'
  # PAGINAS PRINCIPALES (cuenta, inicio, etc.)
  get 'pagina_principal/index'
  get '/cuenta', to: 'pagina_principal#cuenta'
  get '/inicio', to: 'pagina_principal#index'

  # Usuarios
  devise_scope :user do
    get 'users', to: 'devise/sessions#new'
  end
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }, 
                   path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  get 'user/:id', to: 'users#show', as: 'user'

  # Chat
  resources :rooms do
    resources :messages
  end

  resources :pins

  get 'hello_world/index'

  # PRODUCTOS 
  get 'productos', to: 'productos#index'
  get '/productos/new', to: 'productos#new'
  get 'productos/:id', to: 'productos#show', as: 'producto'
  get 'productos/:id/eliminar', to: 'productos#destroy', as: 'eliminar_producto'
  get 'productos/:id/editar', to: 'productos#page_update', as: 'editar_producto'
  get 'productos/:id/favorito', to: 'productos#favoritos', as: 'favoritos_usuario'
  patch 'productos/:id', to: 'productos#update', as: 'update_producto'
  post 'productos', to: 'productos#create'
  get 'producto/populares', to: "productos#mas_visitados", as: "mas_visitados"

  # INTERCAMBIOS
  get 'intercambios', to: 'intercambios#index'
  get 'intercambios/:id/create', to: 'intercambios#create', as: 'crear_intercambio'
  get 'intercambios/:id/eliminar', to: 'intercambios#destroy', as: 'eliminar_intercambio'
  get 'intercambios/:id/editar', to: 'intercambios#page_update', as: 'editar_intercambio'
  patch 'intercambios/:id', to: 'intercambios#update', as: 'update_intercambio'
  post 'intercambios/:id', to: 'intercambios#create', as: 'postear_intercambio'

  # REPORTES
  get "reportes/:id/new", to: "reportes#new", as: "nuevo_reporte"
  get "reportes/:id", to: "reportes#show", as: "ver_reportes"
  post "reportes/:id", to: "reportes#create", as: "crear_reporte"
  get "reporte/:id/editar", to: "reportes#page_update", as: "editar_reporte"
  patch "reporte/:id", to: "reportes#update", as: "actualizar_reporte"
  get "reporte/:id/eliminar", to: "reportes#destroy", as: "eliminar_reporte" 

  # ADMINISTRADOR
  get '/admin', to: 'admins#index'
  get '/admin/productos', to: 'admins#productos'
  get '/admin/reportes', to: 'admins#reportes'
  get '/admin/intercambios', to: 'admins#intercambios'
  get '/admin/usuarios', to: 'admins#usuarios'
  
  # USUARIOS
  get "usuarios/:id/editar", to: "users#page_update", as: "editar_usuario"
  get "usuario/:id", to: "users#cuenta_visita", as: "ver_usuario"
  post "usuario/:id", to: "users#calificar_usuario", as: "calificar_usuario"
  patch "usuarios/:id", to: "users#update", as: "actualizar_usario"
  get "usuarios/:id/eliminar", to: "users#destroy", as: "eliminar_usuario"
  get "usuario/:id/favoritos",  to: "users#favoritos", as: "mostrar_favoritos"
  get "usuario/:id/eliminar_favorito", to: "productos#eliminar_favorito", as: "eliminar_favorito"
end

2023-2-grupo-37/app/views/admins/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Proyecto Grupo 37</title>
  </head>
  <body>
    <%= render 'shared/header' %>
    <main>
        <div class="div-botones-admin">
                <a href="/admin/productos">
                    <button>
                        Mostrar Productos
                        <div class="arrow-wrapper">
                            <div class="arrow"></div>
                        </div>
                    </button>
                </a>

                <a href="/admin/usuarios">
                    <button>
                        Mostrar Usuarios
                        <div class="arrow-wrapper">
                            <div class="arrow"></div>
                        </div>
                    </button>
                </a>

                <a href="/admin/intercambios">
                    <button>
                        Mostrar Intercambios
                        <div class="arrow-wrapper">
                            <div class="arrow"></div>
                        </div>
                    </button>
                </a>

                <a href="/admin/reportes">
                    <button>
                        Mostrar Reportes
                        <div class="arrow-wrapper">
                            <div class="arrow"></div>
                        </div>
                    </button>
                </a>
        </div>
        <div class="btn">Selecciona Una Categoria</div>
    </main>
</body>

2023-2-grupo-37/app/views/admins/intercambios.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Proyecto Grupo 37</title>
  </head>
  <body>
    <%= render 'shared/header' %>
    <main>
        <div class="div-botones-admin">
                <a href="/admin/productos">
                    <button>
                        Mostrar Productos
                        <div class="arrow-wrapper">
                            <div class="arrow"></div>
                        </div>
                    </button>
                </a>

                <a href="/admin/usuarios">
                    <button>
                        Mostrar Usuarios
                        <div class="arrow-wrapper">
                            <div class="arrow"></div>
                        </div>
                    </button>
                </a>

                <a href="/admin/intercambios">
                    <button class="selected">
                        Mostrar Intercambios
                        <div class="arrow-wrapper">
                            <div class="arrow"></div>
                        </div>
                    </button>
                </a>

                <a href="/admin/reportes">
                    <button>
                        Mostrar Reportes
                        <div class="arrow-wrapper">
                            <div class="arrow"></div>
                        </div>
                    </button>
                </a>
        </div>
        
        <section class="element-admin">
            <% if Intercambio.count > 0 %>
                <% @intercambios.each do |intercambio| %>
                    <div class="elements-admin">
                        <h2> Producto: <%= Producto.find(intercambio.producto_id).nombre %></h2>
                        <p> Estado: <%= intercambio.estado %></p>
                        <div class="div-botones-admin-2">
                            <%= button_to 'Editar', editar_intercambio_path(intercambio.id), method: :get %>
                            <%= button_to 'Eliminar', eliminar_intercambio_path(intercambio.id), method: :get %>
                        </div>
                    </div>
                <% end %>
            <% else %>
                <div class="btn">NO HAY INTERCAMBIOS</div>
            <% end %>
        </section>
    </main>

2023-2-grupo-37/app/views/admins/productos.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Proyecto Grupo 37</title>
  </head>
  <body>
    <%= render 'shared/header' %>
    <main>
        <div class="div-botones-admin">
                <a href="/admin/productos">
                    <button class="selected">
                        Mostrar Productos
                        <div class="arrow-wrapper">
                            <div class="arrow"></div>
                        </div>
                    </button>
                </a>

                <a href="/admin/usuarios">
                    <button>
                        Mostrar Usuarios
                        <div class="arrow-wrapper">
                            <div class="arrow"></div>
                        </div>
                    </button>
                </a>

                <a href="/admin/intercambios">
                    <button>
                        Mostrar Intercambios
                        <div class="arrow-wrapper">
                            <div class="arrow"></div>
                        </div>
                    </button>
                </a>

                <a href="/admin/reportes">
                    <button>
                        Mostrar Reportes
                        <div class="arrow-wrapper">
                            <div class="arrow"></div>
                        </div>
                    </button>
                </a>
        </div>
        
        <section class="element-admin">
            <% if @productos.count > 0 %>
                <% @productos.each do |producto| %>
                    <div class="elements-admin">
                        <h2> Nombre Producto: <%= producto.nombre %></h2>
                        <p> Descripcion: <%= producto.descripcion %></p>
                        <div class="div-botones-admin-2">
                            <%= button_to "Editar", editar_producto_path(producto.id), method: :get%> <br>
                            <%= button_to "Eliminar", eliminar_producto_path(producto), method: :get%>
                        </div>
                    </div>
                <% end %>
            <% else %>
                <div class="btn">NO HAY PRODUCTOS</div>
            <% end %>
        </section>
    </main>

2023-2-grupo-37/app/views/admins/reportes.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Proyecto Grupo 37</title>
  </head>
  <body>
    <%= render 'shared/header' %>
    <main>
        <div class="div-botones-admin">
                <a href="/admin/productos">
                    <button>
                        Mostrar Productos
                        <div class="arrow-wrapper">
                            <div class="arrow"></div>
                        </div>
                    </button>
                </a>

                <a href="/admin/usuarios">
                    <button>
                        Mostrar Usuarios
                        <div class="arrow-wrapper">
                            <div class="arrow"></div>
                        </div>
                    </button>
                </a>

                <a href="/admin/intercambios">
                    <button>
                        Mostrar Intercambios
                        <div class="arrow-wrapper">
                            <div class="arrow"></div>
                        </div>
                    </button>
                </a>

                <a href="/admin/reportes">
                    <button class="selected">
                        Mostrar Reportes
                        <div class="arrow-wrapper">
                            <div class="arrow"></div>
                        </div>
                    </button>
                </a>
        </div>
        
        <section class="element-admin">
            <% if @reportes.count > 0 %>
                <% @reportes.each do |reporte| %>
                    <div class="elements-admin">
                        <h2> Producto reportado: <%= Producto.find(reporte.producto_id).nombre %></h2>
                        <p> Motivo: <%= reporte.descripcion %></p>
                        <div class="div-botones-admin-2">
                            <%= button_to 'Editar', editar_reporte_path(reporte.id), method: :get %>
                            <%= button_to 'Eliminar', eliminar_reporte_path(reporte.id), method: :get %>
                        </div>
                    </div>
                <% end %>
            <% else %>
                <div class="btn">NO HAY REPORTES</div>
            <% end %>
        </section>
    </main>
</body>

2023-2-grupo-37/app/views/admins/usuarios.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Proyecto Grupo 37</title>
  </head>
  <body>
    <%= render 'shared/header' %>
    <main>
        <div class="div-botones-admin">
                <a href="/admin/productos">
                    <button>
                        Mostrar Productos
                        <div class="arrow-wrapper">
                            <div class="arrow"></div>
                        </div>
                    </button>
                </a>

                <a href="/admin/usuarios">
                    <button class="selected">
                        Mostrar Usuarios
                        <div class="arrow-wrapper">
                            <div class="arrow"></div>
                        </div>
                    </button>
                </a>

                <a href="/admin/intercambios">
                    <button>
                        Mostrar Intercambios
                        <div class="arrow-wrapper">
                            <div class="arrow"></div>
                        </div>
                    </button>
                </a>

                <a href="/admin/reportes">
                    <button>
                        Mostrar Reportes
                        <div class="arrow-wrapper">
                            <div class="arrow"></div>
                        </div>
                    </button>
                </a>
        </div>
        
        <section class="element-admin">
            <% if @users.count > 0 %>
                <% @users.each do |user| %>
                    <% if !user.admin %>
                        <div class="elements-admin">
                            <h2> Usuario: <%= user.name %></h2>
                            <p> Email: <%= user.email %></p>
                            <div class="div-botones-admin-2">
                                <%= button_to 'Editar', editar_usuario_path(user.id), method: :get %>
                                <%= button_to 'Eliminar', eliminar_usuario_path(user.id), method: :get %>
                            </div>
                        </div>
                    <% end %>
                <% end %>
            <% else %>
                <div class="btn">NO HAY USUARIOS REGISTRADOS</div>
            <% end %>
        </section>
    </main>x