2023-2-grupo-37/config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'rooms/index'
  root 'pagina_principal#index'
  # PAGINAS PRINCIPALES (cuenta, inicio, etc.)
  get 'pagina_principal/index'
  get '/cuenta', to: 'pagina_principal#cuenta'
  get '/inicio', to: 'pagina_principal#index'

  # Usuarios
  devise_scope :user do
    get 'users', to: 'devise/sessions#new'
  end
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }, 
                   path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  get 'user/:id', to: 'users#show', as: 'user'

  # Chat
  resources :rooms do
    resources :messages
  end

  resources :pins

  get 'hello_world/index'

  # PRODUCTOS 
  get 'productos', to: 'productos#index'
  get '/productos/new', to: 'productos#new'
  get 'productos/:id', to: 'productos#show', as: 'producto'
  get 'productos/:id/eliminar', to: 'productos#destroy', as: 'eliminar_producto'
  get 'productos/:id/editar', to: 'productos#page_update', as: 'editar_producto'
  get 'productos/:id/favorito', to: 'productos#favoritos', as: 'favoritos_usuario'
  patch 'productos/:id', to: 'productos#update', as: 'update_producto'
  post 'productos', to: 'productos#create'
  get 'producto/populares', to: "productos#mas_visitados", as: "mas_visitados"

  # INTERCAMBIOS
  get 'intercambios', to: 'intercambios#index'
  get 'intercambios/:id/create', to: 'intercambios#create', as: 'crear_intercambio'
  get 'intercambios/:id/eliminar', to: 'intercambios#destroy', as: 'eliminar_intercambio'
  get 'intercambios/:id/editar', to: 'intercambios#page_update', as: 'editar_intercambio'
  patch 'intercambios/:id', to: 'intercambios#update', as: 'update_intercambio'
  post 'intercambios/:id', to: 'intercambios#create', as: 'postear_intercambio'

  # REPORTES
  get "reportes/:id/new", to: "reportes#new", as: "nuevo_reporte"
  get "reportes/:id", to: "reportes#show", as: "ver_reportes"
  post "reportes/:id", to: "reportes#create", as: "crear_reporte"
  get "reporte/:id/editar", to: "reportes#page_update", as: "editar_reporte"
  patch "reporte/:id", to: "reportes#update", as: "actualizar_reporte"
  get "reporte/:id/eliminar", to: "reportes#destroy", as: "eliminar_reporte" 

  # ADMINISTRADOR
  get '/admin', to: 'admins#index'
  get '/admin/productos', to: 'admins#productos'
  get '/admin/reportes', to: 'admins#reportes'
  get '/admin/intercambios', to: 'admins#intercambios'
  get '/admin/usuarios', to: 'admins#usuarios'
  
  # USUARIOS
  get "usuarios/:id/editar", to: "users#page_update", as: "editar_usuario"
  get "usuario/:id", to: "users#cuenta_visita", as: "ver_usuario"
  post "usuario/:id", to: "users#calificar_usuario", as: "calificar_usuario"
  patch "usuarios/:id", to: "users#update", as: "actualizar_usario"
  get "usuarios/:id/eliminar", to: "users#destroy", as: "eliminar_usuario"
  get "usuario/:id/favoritos",  to: "users#favoritos", as: "mostrar_favoritos"
  get "usuario/:id/eliminar_favorito", to: "productos#eliminar_favorito", as: "eliminar_favorito"
end

2023-2-grupo-37/app/models/user.rb
class User < ApplicationRecord
  has_many :productos, dependent: :destroy 
  has_many :intercambios, through: :productos, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  scope :all_except, ->(user) { where.not(id: user)}
  after_create_commit { broadcast_append_to "users"}
  has_many :messages, dependent: :destroy
  has_many :participants, dependent: :destroy
  after_initialize :inicializar_favs
  
  has_one_attached :image
  # validates :image, attached: true, content_type: ['image/jpeg', 'image/png', 'image/jpg']

  def inicializar_favs
    self.productos_fav ||= {}
  end

  def image_as_thumbnail 
    image.variant(resize_to_limit: [300, 300]).processed
  end

  # attr_accessor :remove_image

  def remove_image
    image.purge_later
  end
end

2023-2-grupo-37/app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

2023-2-grupo-37/app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

2023-2-grupo-37/app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

2023-2-grupo-37/app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
    @user = User.find(resource.id)
    @user.productos_fav = {}
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, 
                                      keys: [:name, :image])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

2023-2-grupo-37/app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

2023-2-grupo-37/app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

2023-2-grupo-37/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @users = User.all_except(current_user)

    @room = Room.new
    @rooms = Room.public_rooms
    @room_name = get_name(@user, current_user)
    @single_room = Room.where(name: @room_name).first || Room.create_private_room([@user, current_user], @room_name)

    @message = Message.new
    @messages = @single_room.messages.order(created_at: :asc)
    render 'rooms/index'
  end
  
  def cuenta_visita
    @user = User.find(params[:id])
  end

  def calificar_usuario
    @user = User.find(params[:id])

    if @user.calificacion == 0
      promedio_estrellas = params[:calificacion].to_i
    else
      promedio_estrellas = (@user.calificacion + params[:calificacion].to_i) / 2
    end

    @user.update(calificacion: promedio_estrellas)
    if @user.save
      redirect_to root_path, notice: 'Calificación actualizada exitosamente.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def page_update
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to root_path, notice: 'Usuario actualizado exitosamente.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def favoritos
    @user = User.find(current_user.id)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path, notice: 'Usuario eliminado exitosamente.'
  end

  private
  def get_name(user1, user2)
    user = [user1, user2].sort
    "private_#{user[0].id}_#{user[1].id}"
  end

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

2023-2-grupo-37/app/helpers/users_helper.rb
module UsersHelper
end

2023-2-grupo-37/app/views/users/_user.html.erb
<div>
    <%= link_to "<strong>#{user.name}</strong>".html_safe, user, style: "color: #845BB3; text-decoration: none;" %>
</div>

2023-2-grupo-37/app/views/users/cuenta_visita.html.erb
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Proyecto Grupo 37</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous">
    <link rel="stylesheet" href="styles.css">
</head>
<body>
  <%= render 'shared/header' %>
  <main>
      <% if user_signed_in? %>
      
        <div class="ordenar">
          <label class="nombre-usuario">
            <%="Calificar a #{@user.name}"%>
          </label>

          <div class="card-client">
            <div class="user-picture">
              <% if @user.image.attached? %>
                <div class="">
                  <%= image_tag(@user.image.variant(resize_to_fit: [150, 150])) %>
                </div>
              <% else %>
                <svg viewBox="0 0 448 512" xmlns="http://www.w3.org/2000/svg">
                  <path d="M224 256c70.7 0 128-57.31 128-128s-57.3-128-128-128C153.3 0 96 57.31 96 128S153.3 
                  256 224 256zM274.7 304H173.3C77.61 304 0 381.6 0 477.3c0 19.14 15.52 34.67 34.66 34.67h378.7C432.5 
                  512 448 496.5 448 477.3C448 381.6 370.4 304 274.7 304z"></path>
                </svg>
              <% end %>
            </div>
            <div class="name-client"> 
              <%= @user.name %> 
            </div>
            <br>
            <div class="estrella-calificacion">
              <%= star_rating(@user.calificacion) %>
            </div>
            <br>
            
            <div class="button-container">
              <%= form_tag({controller: "users", action: "calificar_usuario"}, method: "post") do %>
                <%= select_tag(:calificacion, options_for_select([['⭐️', 1], ['⭐️⭐️', 2], ['⭐️⭐️⭐️', 3], ['⭐️⭐️⭐️⭐️', 4], ['⭐️⭐️⭐️⭐️⭐️', 5]])) %>
                <%= submit_tag "Calificar" %>
              <% end %>
            </div>
            </div>
          </div>
        </div>

      <% else %>
        <div class="fondo_forms">
          <div class="Bienvenida">
            <h1>¡Bienvenido!</h1>
          </div>
          <div class="div-botones">
            <a href="<%= new_user_session_path %>">
              <button>
                Sign in
                <div class="arrow-wrapper">
                  <div class="arrow"></div>
                </div>
              </button>
            </a>

            <a href="<%= new_user_registration_path %>">
              <button>
                Sign up
                <div class="arrow-wrapper">
                  <div class="arrow"></div>
                </div>
              </button>
            </a>
          </div>
        </div>
      <% end %>
  </main>


</body>
</html>

2023-2-grupo-37/app/views/users/favoritos.html.erb
<!-- FILEPATH: /Users/Noam/Desktop/Universidad/Semestre 4/Ingeniería de Software/Proyecto/2023-2-grupo-37/app/views/users/favoritos.html.erb -->
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Proyecto Grupo 37</title>
    <link rel="stylesheet" href="styles.css">
  </head>
  <body>
    <%= render 'shared/header' %>
    <% if user_signed_in? %>
      <main>
        <div class="filtro">
          <a href="/productos">
            <button class="custom-button">
              Todos los Productos
              <div class="arrow-wrapper">
                <div class="arrow"></div>
              </div>
            </button>
          </a>
        </div>
        <section class="intercambios">
          <% if @user.productos_fav.length > 0 %>
            <% @user.productos_fav.each do |fav| %>
              <% if Producto.find(fav[0]).disponible == true %>
                <% producto = Producto.find(fav[0]) %>
                <div class="card">
                  <div class="content">
                    <div class="back">
                      <div class="back-content">
                        <% if producto.image.attached? %>
                          <div class="imagen-producto">
                            <%= image_tag(producto.image.variant(resize_to_fit: [100, 100])) %>
                          </div>
                        <% end %>
                      </div>
                    </div>
                    <div class="front">
                      <div class="img"></div>
                      <div class="front-content">
                        <small class="badge">
                          <strong style="color: black;"> 
                            <%= link_to "#{producto.nombre}", producto_path(producto) %>
                          </strong>
                        </small>
                        <div class="description">
                          <div class="title">
                            <p class="title">
                              <%= "Descripción: #{producto.descripcion}" %>
                            </p>
                          </div>
                          <p class="card-footer"></p>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              <% end %>
            <% end %>
          <% else %>
            <h1 class="btn">NO HAY FAVORITOS</h1>
          <% end %>
        </section>
      </main>
    <% end %>
  </body>
</html>

2023-2-grupo-37/app/views/users/page_update.html.erb
<body>
  <%= render 'shared/header' %>
    <main>
      <div class="fondo_forms">
        <div class="Bienvenida">
            <h1>Editar Usuario</h1>
        </div>
        <%= form_with url: "/usuarios/#{@user.id}", model: @user, method: :patch do |form|%>
          <div class="divform">
            <div>
              <input type="text" id="name" name="user[name]" 
              placeholder="Nombre" class="input" value="<%= @user.name %>">
            </div>
            
            <div>
              <%= form.label :remove_image %>
              <%= form.check_box :remove_image %>
            </div>

            <button type="submit" class="custom-button">
              Actualizar
              <div class="arrow-wrapper">
                <div class="arrow"></div>
              </div>
            </button>
          </div>
        <% end %>
      </div>
    </main>
</body>

2023-2-grupo-37/app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>